language: ruby
rvm:
- 2.1.5
env:
  matrix:
  - DB=mysql MODE=plos SEARCH=plos
  - DB=mysql MODE=default SEARCH=crossref
  - DB=mysql MODE=default SEARCH=plos
  global:
    secure: drRsnsZAyBEb99FBPXPl2GrIJ0QRNvT6BxVnDG/BVulW1DJIRM3rUQYJBPxJIRn+SyEUF5q/z7LYs1alxuTrj0DHeIMY5PGWpm/aQXvUQvQSj5CNfRNdQVWUwjs4xdmg4fJ9anz29CShBo2DfLWvMqWpwX2I/dh6IZQrWmdiI9o=
services:
- memcached
before_script:
- cp .env.travis .env
- mkdir -p tmp/pids
script:
- bundle exec rake db:setup RAILS_ENV=test
- npm install -g bower
- bundle exec rake bower:install:deployment
- bundle exec rspec
addons:
  code_climate:
    repo_token: 996e94d9a86097c853b5bd92197c07cca653d962528e10406f1e75d78517438c
after_failure: cat /home/travis/build/articlemetrics/alm-report/tmp/capybara/*.html
