language: ruby
rvm:
  - 2.1.2

env:
  matrix:
    - DB=mysql
    # - DB=postgresql
  global:
    secure: "agQGmJu7sSCjuBYu/Sbo4a3WoXA2C/BVPoIUneSR2+soFPeyrAFoHOa/EflxIt+uUEApXiodG+u2twFBf07yMVVojluzmONricmjh563gu6rKR9vhE5ZTUYIo3IHdi/w1OTd28uA0T0RpFcxLRbVg2lm5juxE+GjI+QmeROr4lY="

services:
  - memcached

before_script:
  - cp config/settings.yml.travis config/settings.yml
  - cp config/database.yml.travis config/database.yml
  - mkdir -p tmp/pids

script:
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rake spec
  - bundle exec rake test

addons:
  code_climate:
    repo_token: fe7cfe1a913538af13fc5fee3a9244584af63ebf43618322c2bf29f04c00f36c
