defaults: &defaults
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *defaults

test:
  database: <%= ENV["DB_NAME"] %>_test
  <<: *defaults

production:
  <<: *defaults
