# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54088b1eee4451a65e1f89ffccb6b511e8450f2668b41a49e762dbdd81aa80871c68d8e8c52dc256e7b1b21dba24c19be36271a3331cbdbb3fa41ae77185f363

test:
  secret_key_base: a3fecc5dfd8e23d81a1b68de2e73c7719d9954665b85f3b4d5dcd9ae4f5526324578354cf00cc64c8223a28cb043eb5c2b32e91c0a78a5670cf0862043f62741

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
